version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cheerio
    versions:
    - "> 1.0.0.pre.rc.3, < 1.1"
  - dependency-name: css-loader
    versions:
    - ">= 4.a, < 5"
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.2
    - 5.21.0
    - 5.21.1
    - 5.24.0
    - 5.26.0
    - 5.26.1
    - 5.31.1
    - 5.32.0
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: "@types/cheerio"
    versions:
    - 0.22.25
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.24
    - 14.14.26
    - 14.14.29
    - 15.0.0
  - dependency-name: ts-loader
    versions:
    - 8.0.17
    - 8.2.0
    - 9.0.0
    - 9.1.0
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.2.4
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.10
    - 2.5.9
  - dependency-name: nodemon-webpack-plugin
    versions:
    - 4.5.1
