resources:
  - name: fetcher-git
    type: git
    source:
      uri: https://github.com/tlwr/some-gallery-thing.git
      paths:
        - fetcher

jobs:
  - name: build
    serial: true
    plan:
      - get: fetcher-git
        trigger: true
      - task: run-tests
        timeout: 3m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.6.0
          inputs:
            - name: fetcher-git
              path: some-gallery-thing
          run:
            dir: some-gallery-thing/fetcher
            path: sh
            args:
              - -c
              - |
                bundle install
                bundle exec rspec
