name: integration

on:
  push:
    branches: [master]

  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - run: npm install

      - run: npm run test:integration
