name: scrape

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: npm install

      - run: npm run test:integration

      - run: npm run scrape-events
      - run: npm run upload-events
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_EMAIL: ${{secrets.CF_EMAIL }}

      - run: npm run test:smoke
