name: smoke-tests

on:
  push:
    branches: [master]

  schedule:
    - cron: '0 * * * *'

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - run: npm install

      - run: npm run test:smoke
